### ISSUE TITLE
Update Apache Skywalking Action 

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/pipeline-builder#1275]
## Current Behavior

The Skywalking Action uses the wrong Apache CDN. The one it's using now only retains the most recent versions of software, so it breaks older images which is bad.

## Possible Solution

It should switch to the Archive CDN.

https://github.com/paketo-buildpacks/pipeline-builder/blob/main/actions/skywalking-dependency/main.go#L31

**Comment by pivotal-david-osullivan** [comment]
Closed via #1305!
