### ISSUE TITLE
Enable republish_images to have a source tag filter

### ISSUE THREAD

**Issue by dmikusa-pivotal** [paketo-buildpacks/pipeline-builder#537]
## What happened?

At the present moment, the republish_images job will assume that one source repository is used for one buildpack. If you have multiple buildpacks under a source repo then you will be tagging releases with some tag prefix, like `buildpack-a-v1.0` and `buildpack-b-v1.0`. 

This request is so that the job applies a filter like `buildpack-a-*` to fetch the right tag set (using `git tag -l` might be an option in the scripts). It will also need to parse out the version, as we need the version in the scripts. This might require a regex with a capture group, but other options are acceptable too.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

* What buildpacks are you using? Please include versions.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by andrew-su** [comment]
Looks like https://github.com/paketo-buildpacks/pipeline-builder/blob/main/octo/compute-version.sh used by `builder` and `package` may need to be updated to handle tags differently too.
